### ISSUE TITLE
Installation problem - invalid multibyte character

### ISSUE THREAD

**Issue by hatt** [kbingman/paperclipped#25]
When running the db:migrate:extensions task to install, I keep getting the following error. The same goes for any other tasks which use paperclipped.

<pre><code>** Invoke production (first_time)
** Execute production
** Invoke environment (first_time)
** Execute environment
rake aborted!
/home/datl/www/sndemo/vendor/extensions/paperclipped/app/models/asset_tags.rb:208: invalid multibyte char (US-ASCII)
/home/datl/www/sndemo/vendor/extensions/paperclipped/app/models/asset_tags.rb:204: invalid multibyte char (US-ASCII)
/home/datl/www/sndemo/vendor/extensions/paperclipped/app/models/asset_tags.rb:204: syntax error, unexpected $end, expecting keyword_end
    “thumbnail” and “icon” ...
      ^
/usr/lib/ruby/gems/1.9.1/gems/radiant-0.9.1/vendor/rails/activesupport/lib/active_support/dependencies.rb:158:in `require'
/usr/lib/ruby/gems/1.9.1/gems/radiant-0.9.1/vendor/rails/activesupport/lib/active_support/dependencies.rb:158:in `require'
/usr/lib/ruby/gems/1.9.1/gems/radiant-0.9.1/vendor/rails/activesupport/lib/active_support/dependencies.rb:265:in `require_or_load'
/usr/lib/ruby/gems/1.9.1/gems/radiant-0.9.1/vendor/rails/activesupport/lib/active_support/dependencies.rb:425:in `load_missing_constant'
/usr/lib/ruby/gems/1.9.1/gems/radiant-0.9.1/vendor/rails/activesupport/lib/active_support/dependencies.rb:80:in `const_missing_with_dependencies'
/usr/lib/ruby/gems/1.9.1/gems/radiant-0.9.1/vendor/rails/activesupport/lib/active_support/dependencies.rb:92:in `const_missing'
/usr/lib/ruby/gems/1.9.1/gems/radiant-0.9.1/vendor/rails/activesupport/lib/active_support/dependencies.rb:437:in `load_missing_constant'
/usr/lib/ruby/gems/1.9.1/gems/radiant-0.9.1/vendor/rails/activesupport/lib/active_support/dependencies.rb:96:in `const_missing'
/home/datl/www/sndemo/vendor/extensions/paperclipped/paperclipped_extension.rb:27:in `block in activate'
/home/datl/www/sndemo/vendor/extensions/paperclipped/paperclipped_extension.rb:24:in `class_eval'
/home/datl/www/sndemo/vendor/extensions/paperclipped/paperclipped_extension.rb:24:in `activate'
/usr/lib/ruby/gems/1.9.1/gems/radiant-0.9.1/lib/radiant/extension.rb:86:in `activate_extension'
/usr/lib/ruby/gems/1.9.1/gems/radiant-0.9.1/lib/radiant/extension_loader.rb:106:in `each'
/usr/lib/ruby/gems/1.9.1/gems/radiant-0.9.1/lib/radiant/extension_loader.rb:106:in `activate_extensions'
/usr/lib/ruby/gems/1.9.1/gems/radiant-0.9.1/lib/radiant/initializer.rb:201:in `after_initialize'
/usr/lib/ruby/gems/1.9.1/gems/radiant-0.9.1/vendor/rails/railties/lib/initializer.rb:179:in `process'
/usr/lib/ruby/gems/1.9.1/gems/radiant-0.9.1/vendor/rails/railties/lib/initializer.rb:113:in `run'
/usr/lib/ruby/gems/1.9.1/gems/radiant-0.9.1/lib/radiant/initializer.rb:157:in `run'
/home/datl/www/sndemo/config/environment.rb:12:in `<top (required)>'
/usr/lib/ruby/gems/1.9.1/gems/radiant-0.9.1/vendor/rails/activesupport/lib/active_support/dependencies.rb:156:in `require'
/usr/lib/ruby/gems/1.9.1/gems/radiant-0.9.1/vendor/rails/activesupport/lib/active_support/dependencies.rb:156:in `block in require'
/usr/lib/ruby/gems/1.9.1/gems/radiant-0.9.1/vendor/rails/activesupport/lib/active_support/dependencies.rb:521:in `new_constants_in'
/usr/lib/ruby/gems/1.9.1/gems/radiant-0.9.1/vendor/rails/activesupport/lib/active_support/dependencies.rb:156:in `require'
/usr/lib/ruby/gems/1.9.1/gems/radiant-0.9.1/vendor/rails/railties/lib/tasks/misc.rake:4:in `block in <top (required)>'
/usr/lib/ruby/gems/1.9.1/gems/rake-0.8.7/lib/rake.rb:636:in `call'
/usr/lib/ruby/gems/1.9.1/gems/rake-0.8.7/lib/rake.rb:636:in `block in execute'
/usr/lib/ruby/gems/1.9.1/gems/rake-0.8.7/lib/rake.rb:631:in `each'
/usr/lib/ruby/gems/1.9.1/gems/rake-0.8.7/lib/rake.rb:631:in `execute'
/usr/lib/ruby/gems/1.9.1/gems/rake-0.8.7/lib/rake.rb:597:in `block in invoke_with_call_chain'
/usr/lib/ruby/1.9.1/monitor.rb:190:in `mon_synchronize'
/usr/lib/ruby/gems/1.9.1/gems/rake-0.8.7/lib/rake.rb:590:in `invoke_with_call_chain'
/usr/lib/ruby/gems/1.9.1/gems/rake-0.8.7/lib/rake.rb:583:in `invoke'
/usr/lib/ruby/gems/1.9.1/gems/radiant-0.9.1/lib/tasks/environments.rake:10:in `block in <top (required)>'
/usr/lib/ruby/gems/1.9.1/gems/rake-0.8.7/lib/rake.rb:636:in `call'
/usr/lib/ruby/gems/1.9.1/gems/rake-0.8.7/lib/rake.rb:636:in `block in execute'
/usr/lib/ruby/gems/1.9.1/gems/rake-0.8.7/lib/rake.rb:631:in `each'
/usr/lib/ruby/gems/1.9.1/gems/rake-0.8.7/lib/rake.rb:631:in `execute'
/usr/lib/ruby/gems/1.9.1/gems/rake-0.8.7/lib/rake.rb:597:in `block in invoke_with_call_chain'
/usr/lib/ruby/1.9.1/monitor.rb:190:in `mon_synchronize'
/usr/lib/ruby/gems/1.9.1/gems/rake-0.8.7/lib/rake.rb:590:in `invoke_with_call_chain'
/usr/lib/ruby/gems/1.9.1/gems/rake-0.8.7/lib/rake.rb:583:in `invoke'
/usr/lib/ruby/gems/1.9.1/gems/rake-0.8.7/lib/rake.rb:2051:in `invoke_task'
/usr/lib/ruby/gems/1.9.1/gems/rake-0.8.7/lib/rake.rb:2029:in `block (2 levels) in top_level'
/usr/lib/ruby/gems/1.9.1/gems/rake-0.8.7/lib/rake.rb:2029:in `each'
/usr/lib/ruby/gems/1.9.1/gems/rake-0.8.7/lib/rake.rb:2029:in `block in top_level'
/usr/lib/ruby/gems/1.9.1/gems/rake-0.8.7/lib/rake.rb:2068:in `standard_exception_handling'
/usr/lib/ruby/gems/1.9.1/gems/rake-0.8.7/lib/rake.rb:2023:in `top_level'
/usr/lib/ruby/gems/1.9.1/gems/rake-0.8.7/lib/rake.rb:2001:in `block in run'
/usr/lib/ruby/gems/1.9.1/gems/rake-0.8.7/lib/rake.rb:2068:in `standard_exception_handling'
/usr/lib/ruby/gems/1.9.1/gems/rake-0.8.7/lib/rake.rb:1998:in `run'
/usr/lib/ruby/gems/1.9.1/gems/rake-0.8.7/bin/rake:31:in `<top (required)>'
/usr/bin/rake:19:in `load'
/usr/bin/rake:19:in `<main>'</code></pre>

Any help is much appreciated.

**Comment by kbingman** [comment]
Looks like a ruby 1.9 problem to me. This has not been tested on 1.9. I will look into it, but am very busy right now. It does run nicely on 1.8.7

**Comment by dp6ai** [comment]
Pretty sure this is a 1.9 issue, im getting the same error.

Have you looked at a fix at all? 

thanks

DP
